Repository hana-runner/hana-v-backend, pull requests merged in 2024-06, with the labels that each got.

#58 feat: 사용자 관심사 목록 조회 및 거래 내역 API 구현
  src/main/java/com/v/hana/auth/config/SecurityConfig.java
  src/main/java/com/v/hana/command/interest/GetUserInterestTransactionsCommand.java
  src/main/java/com/v/hana/controller/interest/UserInterestController.java
  src/main/java/com/v/hana/dto/interest/TotalPriceDto.java
  src/main/java/com/v/hana/dto/interest/UserInterestDto.java
  src/main/java/com/v/hana/dto/interest/UserInterestResponse.java
  src/main/java/com/v/hana/dto/interest/UserInterestTransactionDto.java
  src/main/java/com/v/hana/dto/interest/UserInterestTransactionsDto.java
  src/main/java/com/v/hana/dto/interest/UserInterestTransactionsResponse.java
  src/main/java/com/v/hana/repository/transaction/TransactionHistoryDetailRepository.java
  src/main/java/com/v/hana/repository/transaction/TransactionHistoryRepository.java
  src/main/java/com/v/hana/service/interest/UserInterestService.java
  src/main/java/com/v/hana/usecase/interest/UserInterestUseCase.java
Labels: feat

#61 feat: 관심사 전체 조회 API 구현
  src/main/java/com/v/hana/command/interest/GetInterestsCommand.java
  src/main/java/com/v/hana/controller/interest/InterestController.java
  src/main/java/com/v/hana/dto/interest/AddUserInterestRequest.java
  src/main/java/com/v/hana/dto/interest/InterestDto.java
  src/main/java/com/v/hana/dto/interest/InterestsResponse.java
  src/main/java/com/v/hana/service/interest/InterestService.java
  src/main/java/com/v/hana/usecase/interest/InterestUseCase.java
Labels: feat

#73 fix: 계좌 등록 API 수정
  src/main/java/com/v/hana/command/account/RegisterAccountCommand.java
  src/main/java/com/v/hana/controller/account/AccountController.java
  src/main/java/com/v/hana/dto/account/AccountCheckResponse.java
  src/main/java/com/v/hana/dto/account/AccountRegisterRequest.java
  src/main/java/com/v/hana/entity/account/Account.java
  src/main/java/com/v/hana/repository/account/AccountApiRepository.java
  src/main/java/com/v/hana/service/account/AccountService.java
Labels: fix

#82 fix: 회원 성별 정보 수정
  src/main/java/com/v/hana/common/constant/Gender.java
  src/main/java/com/v/hana/controller/user/UserController.java
  src/main/java/com/v/hana/dto/user/UserGetResponse.java
Labels: fix

#83 release: docker-compose 생성
  .github/workflows/ci_and_cd.yml
  .github/workflows/pull_request_test.yml
  build.gradle
  docker-compose.yml
  dockerfile
  src/main/java/com/v/hana/auth/util/user/SecurityUtil.java
  src/main/java/com/v/hana/command/account/RegisterAccountCommand.java
  src/main/java/com/v/hana/common/exception/AccountHttpCode.java
  src/main/java/com/v/hana/common/exception/EmailHttpCode.java
  src/main/java/com/v/hana/controller/account/AccountController.java
  src/main/java/com/v/hana/controller/email/EmailController.java
  src/main/java/com/v/hana/controller/interest/UserInterestController.java
  src/main/java/com/v/hana/controller/transaction/TransactionHistoryController.java
  src/main/java/com/v/hana/controller/user/UserController.java
  src/main/java/com/v/hana/dto/account/AccountCheckRequest.java
  src/main/java/com/v/hana/dto/account/AccountRegisterRequest.java
  src/main/java/com/v/hana/dto/interest/UserInterestReportsResponse.java
  src/main/java/com/v/hana/dto/user/UserGetResponse.java
  src/main/java/com/v/hana/entity/account/Account.java
  src/main/java/com/v/hana/entity/account/AccountApi.java
  src/main/java/com/v/hana/event/interest/SumAmountEvent.java
  src/main/java/com/v/hana/event/interest/SumAmountEventListener.java
  src/main/java/com/v/hana/exception/email/InvalidEmailAuthCodeException.java
  src/main/java/com/v/hana/repository/account/AccountApiRepository.java
  src/main/java/com/v/hana/repository/transaction/TransactionHistoryDetailRepository.java
  src/main/java/com/v/hana/service/account/AccountService.java
  src/main/java/com/v/hana/service/interest/UserInterestService.java
  src/main/java/com/v/hana/service/transaction/TransactionHistoryDetailService.java
  src/main/java/com/v/hana/usecase/account/AccountUseCase.java
  src/main/java/com/v/hana/usecase/transaction/TransactionHistoryDetailUseCase.java
  src/main/resources/application.yml
  src/main/resources/db.sql
  src/test/java/com/v/hana/ApplicationTests.java
  src/test/java/com/v/hana/JpaTests.java
  src/test/java/com/v/hana/common/annotation/MethodInfoTest.java
  src/test/java/com/v/hana/common/annotation/TypeInfoTest.java
  src/test/java/com/v/hana/common/config/MySQLTestConfig.java
  src/test/java/com/v/hana/common/config/RedisTestConfig.java
  src/test/java/com/v/hana/common/config/RestDocsTest.java
  src/test/java/com/v/hana/controller/user/UserControllerTest.java
  src/test/java/com/v/hana/docs/example/ExampleControllerTest.java
  src/test/resources/application.yml
Labels: release

#87 fix: 거래내역 관련 API 응답 수정
  src/main/java/com/v/hana/command/account/GetExpenseCommand.java
  src/main/java/com/v/hana/controller/account/AccountController.java
  src/main/java/com/v/hana/controller/transaction/TransactionHistoryController.java
  src/main/java/com/v/hana/dto/account/AccountExpenseResponse.java
  src/main/java/com/v/hana/dto/account/ExpensePerCategory.java
  src/main/java/com/v/hana/dto/transaction/TransactionHistoryDetailDto.java
  src/main/java/com/v/hana/dto/transaction/TransactionHistoryDetailsPostResponse.java
  src/main/java/com/v/hana/dto/transaction/TransactionHistoryGetResponse.java
  src/main/java/com/v/hana/dto/transaction/TransactionHistoryPutResponse.java
  src/main/java/com/v/hana/exception/transaction/ExpenseNotFoundException.java
  src/main/java/com/v/hana/repository/transaction/TransactionHistoryRepository.java
  src/main/java/com/v/hana/service/account/AccountService.java
Labels: fix

#92 fix: 카테고리 API 오류 수정
  .github/workflows/ci_and_cd.yml
  src/main/java/com/v/hana/repository/transaction/TransactionHistoryRepository.java
  src/main/java/com/v/hana/service/transaction/TransactionHistoryService.java
Labels: fix

#93 fix: Swagger 의존성 수정
  build.gradle
  src/main/java/com/v/hana/auth/config/SecurityConfig.java
  src/main/java/com/v/hana/auth/config/SwaggerConfig.java
  src/main/java/com/v/hana/command/example/ExampleCommand.java
  src/main/java/com/v/hana/common/exception/ExampleHttpCode.java
  src/main/java/com/v/hana/controller/example/ExampleController.java
  src/main/java/com/v/hana/dto/example/ExampleRequest.java
  src/main/java/com/v/hana/dto/example/ExampleResponse.java
  src/main/java/com/v/hana/exception/example/ExampleCodeException.java
  src/main/java/com/v/hana/service/example/ExampleService.java
  src/main/java/com/v/hana/usecase/example/ExampleUseCase.java
  src/main/resources/application.yml
  src/main/resources/org/springframework/restdocs/templates/request-fields.snippet
  src/main/resources/org/springframework/restdocs/templates/response-fields.snippet
  src/main/resources/static/docs/RESTDOCS
  src/test/java/com/v/hana/common/config/RestDocsTest.java
  src/test/java/com/v/hana/docs/example/ExampleControllerTest.java
Labels: fix

#95 refactor: 사용자 인증 로직 추가
  src/main/java/com/v/hana/controller/account/AccountController.java
  src/main/java/com/v/hana/controller/interest/UserInterestController.java
  src/main/java/com/v/hana/controller/transaction/TransactionHistoryController.java
Labels: refactor

#97 refactor: 컨트롤러에 swagger 어노테이션 추가
  src/main/java/com/v/hana/controller/account/AccountController.java
  src/main/java/com/v/hana/controller/email/EmailController.java
  src/main/java/com/v/hana/controller/interest/InterestController.java
  src/main/java/com/v/hana/controller/interest/UserInterestController.java
  src/main/java/com/v/hana/controller/transaction/TransactionHistoryController.java
  src/main/java/com/v/hana/controller/user/UserController.java
Labels: refactor

#100 refactor: 계좌 API 관련 응답 객체 수정
  src/main/java/com/v/hana/controller/account/AccountController.java
  src/main/java/com/v/hana/dto/account/AccountDto.java
  src/main/java/com/v/hana/dto/account/AccountRegisterResponse.java
Labels: refactor

#102 feat: 카테고리별 지출에 대한 관심사별 지출 합계 조회 기능
  src/main/java/com/v/hana/controller/account/AccountController.java
  src/main/java/com/v/hana/controller/transaction/TransactionHistoryController.java
  src/main/java/com/v/hana/dto/account/ExpensePerInterest.java
  src/main/java/com/v/hana/dto/account/ExpenseResponse.java
  src/main/java/com/v/hana/repository/transaction/TransactionHistoryDetailRepository.java
  src/main/java/com/v/hana/repository/transaction/TransactionHistoryRepository.java
  src/main/java/com/v/hana/service/account/AccountService.java
  src/main/java/com/v/hana/service/transaction/TransactionHistoryDetailService.java
  src/main/java/com/v/hana/usecase/transaction/TransactionHistoryDetailUseCase.java
Labels: feat

#107 release: 도커 컴포즈로 배포 로직 수정
  src/main/java/com/v/hana/config/RedisConfig.java
  src/main/java/com/v/hana/controller/account/AccountController.java
  src/main/java/com/v/hana/controller/transaction/TransactionHistoryController.java
Labels: release

#110 feat: 사용자 관심사 추가, 수정, 거래 상세 api 구현
  build.gradle
  src/main/java/com/v/hana/command/interest/AddUserInterestCommand.java
  src/main/java/com/v/hana/command/interest/ModifyUserInterestCommand.java
  src/main/java/com/v/hana/common/config/S3Config.java
  src/main/java/com/v/hana/common/exception/ImageHttpCode.java
  src/main/java/com/v/hana/common/exception/InterestHttpCode.java
  src/main/java/com/v/hana/common/exception/UserInterestHttpCode.java
  src/main/java/com/v/hana/common/response/PutSuccessResponse.java
  src/main/java/com/v/hana/controller/interest/UserInterestController.java
  src/main/java/com/v/hana/dto/interest/AddUserInterestRequest.java
  src/main/java/com/v/hana/dto/interest/AddUserInterestResponse.java
  src/main/java/com/v/hana/entity/interest/UserInterest.java
  src/main/java/com/v/hana/exception/interest/ImageException.java
  src/main/java/com/v/hana/exception/interest/InterestNotExistedException.java
  src/main/java/com/v/hana/exception/interest/UserInterestDuplicatedException.java
  src/main/java/com/v/hana/repository/interest/UserInterestRepository.java
  src/main/java/com/v/hana/service/interest/ImageService.java
  src/main/java/com/v/hana/service/interest/UserInterestService.java
  src/main/java/com/v/hana/usecase/interest/UserInterestUseCase.java
  src/main/resources/application.yml
Labels: feat

#111 modify: 카테고리별 지출 관심사 상세 응답 객체 이름 수정
  src/main/java/com/v/hana/dto/account/ExpensePerInterest.java
  src/main/java/com/v/hana/repository/transaction/TransactionHistoryDetailRepository.java
Labels: modify

#113 fix: 사용자 관심사별 거래 내역 소비 조회 API 수정
  src/main/java/com/v/hana/controller/interest/UserInterestController.java
Labels: fix

#115 fix: 사용자 관심사별 거래 내역 소비 조회 DTO 수정
  .github/workflows/ci_and_cd.yml
  src/main/java/com/v/hana/dto/interest/UserInterestReportsDto.java
  src/main/java/com/v/hana/dto/interest/UserInterestReportsResponse.java
  src/main/java/com/v/hana/event/interest/SumAmountEventListener.java
  src/main/resources/application.yml
Labels: fix

#117 release: 환경 변수 수정
  .github/workflows/ci_and_cd.yml
Labels: release

#119 fix: 사용자 관심사별 거래 내역 소비 조회 DTO 수정
  src/main/java/com/v/hana/dto/interest/UserInterestReportsDto.java
  src/main/java/com/v/hana/event/interest/SumAmountEventListener.java
Labels: fix

#121 fix: 사용자 관심사별 거래 내역 소비 조회 로직 수정
  src/main/java/com/v/hana/event/interest/SumAmountEventListener.java
Labels: fix

#123 fix: 사용자 관심사별 거래 내역 상세 조회 로직 수정
  src/main/java/com/v/hana/controller/interest/UserInterestController.java
  src/main/java/com/v/hana/dto/interest/MyMouthDto.java
  src/main/java/com/v/hana/dto/interest/UserInterestReportsDto.java
  src/main/java/com/v/hana/event/interest/SumAmountEventListener.java
  src/main/java/com/v/hana/service/transaction/TransactionHistoryDetailService.java
Labels: fix

#130 fix: 사용자 관심사별 거래 내역 소비 조회 로직 수정
  src/main/java/com/v/hana/controller/interest/UserInterestController.java
  src/main/java/com/v/hana/dto/card/CardInterestResponse.java
  src/main/java/com/v/hana/entity/card/Card.java
  src/main/java/com/v/hana/repository/transaction/TransactionHistoryDetailRepository.java
  src/main/resources/db.sql
Labels: fix

#132 fix: 카드 API 수정
  src/main/java/com/v/hana/dto/card/CardDto.java
  src/main/java/com/v/hana/dto/card/CardInterestResponse.java
  src/main/java/com/v/hana/entity/card/Card.java
  src/main/java/com/v/hana/entity/card/CardBenefit.java
  src/main/java/com/v/hana/repository/card/CardBenefitRepository.java
  src/main/java/com/v/hana/repository/card/CardInterestRepository.java
  src/main/java/com/v/hana/repository/card/CardRepository.java
  src/main/java/com/v/hana/repository/transaction/TransactionHistoryDetailRepository.java
  src/main/java/com/v/hana/service/card/CardInterestService.java
  src/main/java/com/v/hana/service/transaction/TransactionHistoryDetailService.java
Labels: fix

#135 fix: 관심사 거래 내역 api 오류 수정
  src/main/java/com/v/hana/dto/interest/UserInterestTransactionsDto.java
  src/main/java/com/v/hana/repository/interest/InterestRepository.java
  src/main/java/com/v/hana/repository/transaction/TransactionHistoryRepository.java
  src/main/java/com/v/hana/service/interest/UserInterestService.java
Labels: fix

#138 feat: 카드 추천 API 구현
  src/main/java/com/v/hana/dto/card/CardBenefitDto.java
  src/main/java/com/v/hana/dto/card/CardDto.java
  src/main/java/com/v/hana/repository/card/CardBenefitRepository.java
  src/main/java/com/v/hana/repository/card/CardInterestRepository.java
  src/main/java/com/v/hana/service/card/CardInterestService.java
Labels: feat

#144 style: swagger 어노테이션 추가
  src/main/java/com/v/hana/controller/fcm/FcmController.java
  src/main/java/com/v/hana/controller/interest/UserInterestController.java
  src/main/java/com/v/hana/controller/user/UserController.java
Labels: style

#146 fix: 계좌 거래 내역 조회 API 수정
  src/main/java/com/v/hana/event/account/ReadAccountTransactionEventListener.java
  src/main/java/com/v/hana/repository/transaction/TransactionHistoryDetailRepository.java
  src/main/java/com/v/hana/repository/transaction/TransactionHistoryRepository.java
  src/main/java/com/v/hana/service/transaction/TransactionHistoryDetailService.java
  src/main/java/com/v/hana/service/transaction/TransactionHistoryService.java
Labels: fix

#149 feat: 관심사별 카테고리 지출 내역 비교 분석
  src/main/java/com/v/hana/controller/interest/UserInterestController.java
  src/main/java/com/v/hana/dto/interest/UserCompareResponse.java
  src/main/java/com/v/hana/dto/interest/UserComparison.java
  src/main/java/com/v/hana/repository/transaction/TransactionHistoryDetailRepository.java
  src/main/java/com/v/hana/service/interest/UserInterestService.java
  src/main/java/com/v/hana/usecase/interest/UserInterestUseCase.java
Labels: feat

#153 fix: s3 오류 수정
  src/main/java/com/v/hana/controller/interest/UserInterestController.java
  src/main/java/com/v/hana/repository/interest/UserInterestRepository.java
  src/main/java/com/v/hana/repository/transaction/TransactionHistoryDetailRepository.java
  src/main/java/com/v/hana/service/interest/ImageService.java
  src/main/java/com/v/hana/service/interest/UserInterestService.java
  src/main/resources/application.yml
Labels: fix

#154 refactor: 관심사별 카테고리 지출 비교 분석 로직 수정
  src/main/java/com/v/hana/controller/interest/UserInterestController.java
  src/main/java/com/v/hana/repository/transaction/TransactionHistoryDetailRepository.java
  src/main/java/com/v/hana/service/interest/UserInterestService.java
  src/main/java/com/v/hana/usecase/interest/UserInterestUseCase.java
Labels: refactor

#157 refactor: 비교 데이터 dto 성별 추가
  src/main/java/com/v/hana/controller/interest/UserInterestController.java
  src/main/java/com/v/hana/dto/alarm/Notification.java
  src/main/java/com/v/hana/dto/interest/UserCompareResponse.java
  src/main/java/com/v/hana/dto/interest/UserComparisonDto.java
  src/main/java/com/v/hana/repository/transaction/TransactionHistoryDetailRepository.java
  src/main/java/com/v/hana/service/fcm/GetValidNotificationService.java
  src/main/java/com/v/hana/service/interest/UserInterestService.java
  src/main/java/com/v/hana/usecase/interest/UserInterestUseCase.java
Labels: refactor

#158 fix: InterestId null 값 수정
  src/main/java/com/v/hana/service/interest/UserInterestService.java
Labels: fix

#163 fix: 사용자 관심사 거래 내역 api 수정
  src/main/java/com/v/hana/repository/interest/UserInterestRepository.java
  src/main/java/com/v/hana/repository/transaction/TransactionHistoryDetailRepository.java
  src/main/java/com/v/hana/service/interest/UserInterestService.java
Labels: fix
