Repository hana-runner/hana-v-backend, pull requests merged in 2024-05, with the labels that each got.

#5 chore: 프로젝트 로깅 설정
  build.gradle
  src/main/java/com/v/hana/Application.java
  src/main/java/com/v/hana/common/annotation/MethodInfo.java
  src/main/java/com/v/hana/common/annotation/TypeInfo.java
  src/main/java/com/v/hana/common/aspect/LoggerAspect.java
  src/main/java/com/v/hana/common/config/AspectConfig.java
  src/main/resources/application.yml
  src/main/resources/log4j2.xml
  src/test/java/com/v/hana/ApplicationTests.java
  src/test/java/com/v/hana/common/annotation/MethodInfoTest.java
  src/test/java/com/v/hana/common/annotation/TypeInfoTest.java
Labels: fix, chore

#7 chore: 프로젝트 코드 커버리지 설정
  .github/workflows/pull_request_test.yml
  build.gradle
  jacoco.gradle
  sonarqube.gradle
Labels: chore

#12 chore: 프로젝트 서버 설정
  .gitignore
  build.gradle
  src/main/java/com/v/hana/common/response/BaseHttpCode.java
  src/main/java/com/v/hana/common/response/BaseHttpReason.java
  src/main/java/com/v/hana/common/response/BaseResponse.java
  src/main/java/com/v/hana/common/response/GlobalHttpCode.java
  src/main/java/com/v/hana/controller/example/ExampleController.java
  src/main/java/com/v/hana/dto/example/ExampleRequestDto.java
  src/main/java/com/v/hana/dto/example/ExampleResponseDto.java
  src/main/java/com/v/hana/service/example/ExampleService.java
  src/main/resources/application.yml
  src/main/resources/org/springframework/restdocs/templates/request-fields.snippet
  src/main/resources/org/springframework/restdocs/templates/response-fields.snippet
  src/main/resources/static/docs/RESTDOCS
  src/test/java/com/v/hana/docs/RestDocsTest.java
  src/test/java/com/v/hana/docs/example/ExampleControllerTest.java
Labels: chore

#14 chore: 프로젝트 내 예외 처리
  build.gradle
  src/main/java/com/v/hana/command/example/ExampleCommand.java
  src/main/java/com/v/hana/common/dto/SelfValidating.java
  src/main/java/com/v/hana/common/exception/BaseCodeException.java
  src/main/java/com/v/hana/common/exception/BaseExceptionResponse.java
  src/main/java/com/v/hana/common/exception/ExampleHttpCode.java
  src/main/java/com/v/hana/common/exception/ExceptionControllerAdvice.java
  src/main/java/com/v/hana/common/response/BaseResponse.java
  src/main/java/com/v/hana/controller/example/ExampleController.java
  src/main/java/com/v/hana/dto/example/ExampleRequest.java
  src/main/java/com/v/hana/dto/example/ExampleRequestDto.java
  src/main/java/com/v/hana/dto/example/ExampleResponse.java
  src/main/java/com/v/hana/dto/example/ExampleResponseDto.java
  src/main/java/com/v/hana/exception/example/ExampleCodeException.java
  src/main/java/com/v/hana/service/example/ExampleService.java
  src/main/java/com/v/hana/usecase/example/ExampleUseCase.java
  src/test/java/com/v/hana/docs/example/ExampleControllerTest.java
Labels: chore

#24 refactor: 예외 처리 핸들링 방식 변경
  build.gradle
  dockerfile
  src/main/java/com/v/hana/common/dto/SelfValidating.java
  src/main/java/com/v/hana/common/exception/ExceptionControllerAdvice.java
  src/main/java/com/v/hana/controller/example/ExampleController.java
  src/main/java/com/v/hana/dto/example/ExampleRequest.java
Labels: refactor

#29 fix: Parameter 0 of constructor 오류 해결
  src/main/java/com/v/hana/Application.java
  src/main/java/com/v/hana/common/config/JpaConfig.java
  src/main/resources/application.yml
  src/main/resources/db.sql
Labels: fix

#32 chore: Webconfig 추가
  src/main/java/com/v/hana/common/config/WebConfig.java
Labels: chore

#38 feat: 단일 거래 조회 API #27
  src/main/java/com/v/hana/command/transaction/ReadTransactionHistoryByIdCommend.java
  src/main/java/com/v/hana/command/transaction/ReadTransactionHistoryDetailsByIdCommend.java
  src/main/java/com/v/hana/common/config/ApplicationEventConfig.java
  src/main/java/com/v/hana/common/config/EnableAsyncConfig.java
  src/main/java/com/v/hana/common/event/BaseEvent.java
  src/main/java/com/v/hana/common/exception/TransactionHttpCode.java
  src/main/java/com/v/hana/controller/example/ExampleController.java
  src/main/java/com/v/hana/controller/transaction/TransactionHistoryController.java
  src/main/java/com/v/hana/dto/transaction/TransactionHistoryGetRequest.java
  src/main/java/com/v/hana/dto/transaction/TransactionHistoryGetResponse.java
  src/main/java/com/v/hana/entity/BaseTimeEntity.java
  src/main/java/com/v/hana/entity/account/Account.java
  src/main/java/com/v/hana/entity/category/Category.java
  src/main/java/com/v/hana/entity/interest/Interest.java
  src/main/java/com/v/hana/entity/transaction/TransactionHistory.java
  src/main/java/com/v/hana/entity/transaction/TransactionHistoryDetail.java
  src/main/java/com/v/hana/exception/transaction/TransactionIdNotFoundException.java
  src/main/java/com/v/hana/repository/account/AccountRepository.java
  src/main/java/com/v/hana/repository/category/CategoryRepository.java
  src/main/java/com/v/hana/repository/interest/InterestRepository.java
  src/main/java/com/v/hana/repository/transaction/TransactionHistoryDetailRepository.java
  src/main/java/com/v/hana/repository/transaction/TransactionHistoryRepository.java
  src/main/java/com/v/hana/service/transaction/TransactionHistoryDetailService.java
  src/main/java/com/v/hana/service/transaction/TransactionHistoryService.java
  src/main/java/com/v/hana/usecase/transaction/TransactionHistoryDetailUseCase.java
  src/main/java/com/v/hana/usecase/transaction/TransactionHistoryUseCase.java
  src/main/resources/db.sql
  src/main/resources/dummy.sql
Labels: feat

#41 feat: 단일 거래에 대한 카테고리 수정 API 구현
  src/main/java/com/v/hana/command/category/FindCategoryByIdCommand.java
  src/main/java/com/v/hana/command/transaction/UpdateTransactionHistoryCommand.java
  src/main/java/com/v/hana/common/exception/CategoryHttpCode.java
  src/main/java/com/v/hana/controller/transaction/TransactionHistoryController.java
  src/main/java/com/v/hana/dto/transaction/TransactionHistoryGetRequest.java
  src/main/java/com/v/hana/dto/transaction/TransactionHistoryPutRequest.java
  src/main/java/com/v/hana/dto/transaction/TransactionHistoryPutResponse.java
  src/main/java/com/v/hana/exception/category/CategoryIdNotFoundException.java
  src/main/java/com/v/hana/service/category/CategoryService.java
  src/main/java/com/v/hana/service/transaction/TransactionHistoryService.java
  src/main/java/com/v/hana/usecase/category/CategoryUseCase.java
  src/main/java/com/v/hana/usecase/transaction/TransactionHistoryUseCase.java
Labels: feat

#42 feat: Custom Exception 추가
  src/main/java/com/v/hana/common/exception/BaseCodeException.java
  src/main/java/com/v/hana/exception/user/controllerAdvice/UserExceptionControllerAdvice.java
  src/main/resources/application.yml
Labels: feat, refactor

#43 feat: 사용자 관심사 목록 api 구현
  build.gradle
  src/main/java/com/v/hana/controller/UserInterestController.java
  src/main/java/com/v/hana/dto/UserInterestDto.java
  src/main/java/com/v/hana/dto/UserInterestResponse.java
  src/main/java/com/v/hana/dto/example/ExampleRequest.java
  src/main/java/com/v/hana/entity/BaseTimeEntity.java
  src/main/java/com/v/hana/entity/interest/UserInterest.java
  src/main/java/com/v/hana/repository/interest/UserInterestRepository.java
  src/main/java/com/v/hana/service/interest/UserInterestService.java
  src/main/resources/db.sql
Labels: feat
